name: Test LLM Response Timer Action

on:
  workflow_dispatch: 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run LLM Response Timer Action
        uses: ./actions/timer
        with:
          api_url: 'http://localhost:1234/v1/chat/completions'
          prompt_file: './prompts/action_prompt1.0.txt'
